#!/bin/bash
# viewer-build.sh — scans runs/ and emits viewer-data.js for viewer.html
# Usage: ./viewer-build.sh [runs-dir]

set -euo pipefail

SOURCE="$0"
while [ -L "$SOURCE" ]; do
  TARGET=$(readlink "$SOURCE")
  if [[ "$TARGET" = /* ]]; then SOURCE="$TARGET"; else SOURCE="$(dirname "$SOURCE")/$TARGET"; fi
done
SCRIPT_DIR="$(cd "$(dirname "$SOURCE")" && pwd)"

RUNS_DIR="${1:-$SCRIPT_DIR/runs}"
OUT="$SCRIPT_DIR/viewer-data.js"
# Derive briefs/rubrics from runs-dir parent (so cross-install scans work)
RUNS_PARENT="$(cd "$RUNS_DIR/.." && pwd)"
BRIEFS_DIR="${RUNS_PARENT}/briefs"
RUBRICS_DIR="${RUNS_PARENT}/rubrics"
# Fallback to script-local if not found
[ ! -d "$BRIEFS_DIR" ] && BRIEFS_DIR="$SCRIPT_DIR/briefs"
[ ! -d "$RUBRICS_DIR" ] && RUBRICS_DIR="$SCRIPT_DIR/rubrics"

if [ ! -d "$RUNS_DIR" ]; then
  echo "ERROR: runs dir not found: $RUNS_DIR" >&2
  exit 1
fi

b64() { /usr/bin/base64 < "$1" | /usr/bin/tr -d '\n'; }

mtime_epoch() {
  /usr/bin/stat -f %m "$1" 2>/dev/null || echo "0"
}

mtime_iso() {
  local epoch="$1"
  /bin/date -u -r "$epoch" -j -f %s '+%Y-%m-%dT%H:%M:%SZ' 2>/dev/null || echo ""
}

get_field() {
  local file="$1" key="$2"
  /usr/bin/grep -m1 -E "^${key}:" "$file" 2>/dev/null | /usr/bin/sed "s/^${key}: *//; s/[[:space:]]*$//" || true
}

get_feedback_score() {
  local file="$1"
  local s
  s=$(/usr/bin/grep -m1 -E '\*\*TOTAL\*\*' "$file" 2>/dev/null | /usr/bin/grep -oE '[0-9]+\.[0-9]+' | /usr/bin/tail -1 || true)
  if [ -z "$s" ]; then
    s=$(/usr/bin/grep -m1 -oE '"weighted_total":[[:space:]]*[0-9]+\.?[0-9]*' "$file" 2>/dev/null | /usr/bin/grep -oE '[0-9]+\.?[0-9]*' || true)
  fi
  echo "${s:-0}"
}

get_feedback_verdict() {
  local file="$1"
  local v
  v=$(/usr/bin/grep -m1 -E '## Verdict:' "$file" 2>/dev/null | /usr/bin/sed -E 's/.*Verdict:[[:space:]]*//; s/[[:space:]]*\(.*//' | /usr/bin/awk '{print $1}' || true)
  if [ -z "$v" ]; then
    v=$(/usr/bin/grep -m1 -oE '"verdict":[[:space:]]*"[^"]+"' "$file" 2>/dev/null | /usr/bin/sed -E 's/.*"verdict":[[:space:]]*"([^"]+)".*/\1/' || true)
  fi
  echo "${v:-?}"
}

# Extract score breakdown rows from feedback markdown table
# Returns JSON array: [{"criterion":"...","score":"X/10","weight":0.22,"weighted":1.98}]
get_score_breakdown() {
  local file="$1"
  /usr/bin/awk '
    BEGIN { in_table=0; out="["; first=1 }
    /^\| Criterion/ { in_table=1; next }
    /^\|[-: ]+\|[-: ]+\|[-: ]+\|[-: ]+\|/ { if(in_table) next }
    in_table && /^\|/ {
      n = split($0, parts, "|")
      if (n >= 5) {
        crit = parts[2]; gsub(/^[ \t]+|[ \t]+$/, "", crit)
        sc   = parts[3]; gsub(/^[ \t]+|[ \t]+$/, "", sc)
        wt   = parts[4]; gsub(/^[ \t]+|[ \t]+$/, "", wt)
        wtd  = parts[5]; gsub(/^[ \t]+|[ \t]+$/, "", wtd)
        if (crit ~ /\*\*TOTAL\*\*/ || crit ~ /^TOTAL$/) { in_table=0; next }
        if (crit == "" || crit == "Criterion") next
        gsub(/"/, "\\\"", crit); gsub(/"/, "\\\"", sc)
        if (!first) out = out ","
        out = out "{\"criterion\":\"" crit "\",\"score\":\"" sc "\",\"weight\":\"" wt "\",\"weighted\":\"" wtd "\"}"
        first = 0
      }
    }
    in_table && /^[^|]/ && !/^$/ { in_table=0 }
    END { print out "]" }
  ' "$file"
}

# Count issues by tier — single integer per tier, no newlines
get_issue_counts() {
  local file="$1"
  /usr/bin/awk '
    BEGIN { c=0; m=0; n=0; flag="" }
    /^#+[[:space:]]*[Cc]ritical/ { flag="c"; next }
    /^#+[[:space:]]*[Mm]ajor/    { flag="m"; next }
    /^#+[[:space:]]*[Mm]inor/    { flag="n"; next }
    /^#+[[:space:]]/             { flag=""; next }
    flag != "" && /^[[:space:]]*([0-9]+\.|[-*])[[:space:]]/ {
      if (flag=="c") c++
      else if (flag=="m") m++
      else if (flag=="n") n++
    }
    END { printf "{\"critical\":%d,\"major\":%d,\"minor\":%d}", c, m, n }
  ' "$file" 2>/dev/null || /bin/echo "{\"critical\":0,\"major\":0,\"minor\":0}"
}

# Extract profile + threshold from brief frontmatter
get_brief_profile() {
  local file="$1"
  /usr/bin/awk '/^---/{c++; next} c==1 && /^profile:/{gsub(/profile:[[:space:]]*/,""); print; exit}' "$file" 2>/dev/null || echo ""
}
get_brief_threshold() {
  local file="$1"
  /usr/bin/awk '/^---/{c++; next} c==1 && /^threshold:/{gsub(/threshold:[[:space:]]*/,""); print; exit}' "$file" 2>/dev/null || echo ""
}

js_str() {
  /usr/bin/awk 'BEGIN{ORS=""} {gsub(/\\/,"\\\\"); gsub(/"/,"\\\""); gsub(/\n/,"\\n"); print}' <<< "$1"
}

# File size, word count, line count
file_stats() {
  local f="$1"
  if [ -f "$f" ]; then
    local words lines bytes
    words=$(/usr/bin/awk '{c+=NF} END{print c+0}' "$f" 2>/dev/null)
    lines=$(/usr/bin/awk 'END{print NR+0}' "$f" 2>/dev/null)
    bytes=$(/usr/bin/wc -c < "$f" 2>/dev/null | /usr/bin/tr -d ' ')
    echo "{\"words\":${words:-0},\"lines\":${lines:-0},\"bytes\":${bytes:-0}}"
  else
    echo "{\"words\":0,\"lines\":0,\"bytes\":0}"
  fi
}

# Begin output
{
  echo "// Auto-generated by viewer-build.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "window.GAN_RUNS = ["
} > "$OUT"

count=0
for run_dir in "$RUNS_DIR"/*/; do
  [ -d "$run_dir" ] || continue
  run_id=$(/usr/bin/basename "$run_dir")
  summary="$run_dir/run-summary.md"
  draft="$run_dir/draft.md"
  state="$run_dir/generator-state.md"

  task=""; date=""; score="0"; verdict="?"; iters="?"; cleanup_status=""
  if [ -f "$summary" ]; then
    task=$(get_field "$summary" "Task")
    date=$(get_field "$summary" "Date")
    iters=$(get_field "$summary" "Iterations")
    verdict=$(get_field "$summary" "Verdict" | /usr/bin/awk '{print $1}')
    cleanup_status=$(get_field "$summary" "Final-Cleanup")
    score=$(/usr/bin/grep -m1 -oE '[0-9]+\.[0-9]+ */ *10' "$summary" 2>/dev/null | /usr/bin/grep -oE '[0-9]+\.[0-9]+' | /usr/bin/head -1 || true)
    score="${score:-0}"
  fi

  # Try to get start/end epoch
  start_epoch=$(/bin/echo "$run_id" | /usr/bin/awk -F- '{
    # run_id format: YYYYMMDD-HHMMSS-task or YYYYMMDD-HHMMSS-task-name
    y=substr($1,1,4); mo=substr($1,5,2); d=substr($1,7,2)
    h=substr($2,1,2); mi=substr($2,3,2); s=substr($2,5,2)
    cmd=sprintf("date -j -f %%Y%%m%%d%%H%%M%%S %s%s%s%s%s%s +%%s 2>/dev/null", y, mo, d, h, mi, s)
    cmd | getline epoch
    close(cmd)
    print epoch
  }')
  end_epoch=$(mtime_epoch "$summary")
  [ -z "$start_epoch" ] && start_epoch="0"
  [ -z "$end_epoch" ] && end_epoch="0"

  # File-level metadata
  draft_b64=""; draft_stats="{\"words\":0,\"lines\":0,\"bytes\":0}"
  if [ -f "$draft" ]; then draft_b64=$(b64 "$draft"); draft_stats=$(file_stats "$draft"); fi

  summary_b64=""; if [ -f "$summary" ]; then summary_b64=$(b64 "$summary"); fi
  state_b64=""; if [ -f "$state" ]; then state_b64=$(b64 "$state"); fi

  # Brief and rubric — find by frontmatter task: field (filenames may differ)
  brief_b64=""; rubric_b64=""; brief_profile=""; brief_threshold=""
  rubric_mtime="0"; brief_mtime="0"
  brief_filename=""; rubric_filename=""
  if [ -n "$task" ]; then
    # First try direct filename match
    bf="$BRIEFS_DIR/${task}.md"
    if [ ! -f "$bf" ]; then
      # Fallback: scan briefs/ for one whose frontmatter task: matches
      for candidate in "$BRIEFS_DIR"/*.md; do
        [ -f "$candidate" ] || continue
        cand_task=$(/usr/bin/awk '/^---/{c++; next} c==1 && /^task:/{gsub(/task:[[:space:]]*/,""); gsub(/[[:space:]]+$/,""); print; exit}' "$candidate" 2>/dev/null)
        if [ "$cand_task" = "$task" ]; then bf="$candidate"; break; fi
      done
    fi
    if [ -f "$bf" ]; then
      brief_b64=$(b64 "$bf")
      brief_profile=$(get_brief_profile "$bf")
      brief_threshold=$(get_brief_threshold "$bf")
      brief_mtime=$(mtime_epoch "$bf")
      brief_filename=$(/usr/bin/basename "$bf")
    fi
    rf="$RUBRICS_DIR/${task}-rubric.md"
    if [ -f "$rf" ]; then
      rubric_b64=$(b64 "$rf")
      rubric_mtime=$(mtime_epoch "$rf")
      rubric_filename=$(/usr/bin/basename "$rf")
    fi
  fi

  # Iterations: build array with score breakdown + issues + mtime
  feedbacks_json=""
  if [ -d "$run_dir/feedback" ]; then
    for fb in "$run_dir/feedback"/feedback-*.md; do
      [ -f "$fb" ] || continue
      fb_name=$(/usr/bin/basename "$fb")
      iter_num=$(echo "$fb_name" | /usr/bin/grep -oE '[0-9]+' | /usr/bin/sed 's/^0*//')
      [ -z "$iter_num" ] && iter_num=0
      fb_score=$(get_feedback_score "$fb")
      fb_verdict=$(get_feedback_verdict "$fb")
      fb_b64=$(b64 "$fb")
      fb_breakdown=$(get_score_breakdown "$fb")
      fb_issues=$(get_issue_counts "$fb")
      fb_mtime=$(mtime_epoch "$fb")
      fb_words=$(/usr/bin/awk '{c+=NF} END{print c+0}' "$fb" 2>/dev/null)

      # Per-iter draft + state snapshots (only present if loop-operator was patched)
      iter_pad=$(printf '%03d' "$iter_num")
      iter_draft="$run_dir/drafts/draft-iter-${iter_pad}.md"
      iter_state="$run_dir/drafts/state-iter-${iter_pad}.md"
      iter_draft_b64=""
      iter_state_b64=""
      iter_draft_words=0
      [ -f "$iter_draft" ] && iter_draft_b64=$(b64 "$iter_draft") && iter_draft_words=$(/usr/bin/awk '{c+=NF} END{print c+0}' "$iter_draft" 2>/dev/null)
      [ -f "$iter_state" ] && iter_state_b64=$(b64 "$iter_state")

      feedbacks_json+="{\"iter\":${iter_num},\"score\":${fb_score:-0},\"verdict\":\"${fb_verdict}\",\"content_b64\":\"${fb_b64}\",\"breakdown\":${fb_breakdown},\"issues\":${fb_issues},\"mtime\":${fb_mtime},\"words\":${fb_words:-0},\"iter_draft_b64\":\"${iter_draft_b64}\",\"iter_state_b64\":\"${iter_state_b64}\",\"iter_draft_words\":${iter_draft_words:-0}},"
    done
    feedbacks_json="${feedbacks_json%,}"
  fi

  if ! [[ "$score" =~ ^[0-9]+(\.[0-9]+)?$ ]]; then score="0"; fi

  cat >> "$OUT" <<EOF
{
"id": "$(js_str "$run_id")",
"task": "$(js_str "$task")",
"date": "$(js_str "$date")",
"iterations": "$(js_str "$iters")",
"score": ${score},
"verdict": "$(js_str "$verdict")",
"cleanup_status": "$(js_str "$cleanup_status")",
"profile": "$(js_str "$brief_profile")",
"threshold": "$(js_str "$brief_threshold")",
"brief_filename": "$(js_str "$brief_filename")",
"rubric_filename": "$(js_str "$rubric_filename")",
"start_epoch": ${start_epoch:-0},
"end_epoch": ${end_epoch:-0},
"brief_mtime": ${brief_mtime:-0},
"rubric_mtime": ${rubric_mtime:-0},
"draft_stats": ${draft_stats},
"draft_b64": "${draft_b64}",
"summary_b64": "${summary_b64}",
"state_b64": "${state_b64}",
"brief_b64": "${brief_b64}",
"rubric_b64": "${rubric_b64}",
"feedbacks": [${feedbacks_json}]
},
EOF
  count=$((count + 1))
done

{
  echo "];"
  echo "console.log('GAN_RUNS loaded:', window.GAN_RUNS.length);"
} >> "$OUT"

echo "viewer-data.js written: $count runs → $OUT"
echo "Open: file://$SCRIPT_DIR/viewer.html"
